### ISSUE TITLE
Tool - Vaulting Solution

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/ubiquitous-journey#18]
- Hashicorp Vault

_NOT_ sealed secrets

**Comment by springdo** [comment]
@adamclark did you manage to get a look at any of the Vaulting solutions for SEcret Management yesterday?

**Comment by adamclark** [comment]
@springdo not yet but will start looking at it today

**Comment by tylerauerbeck** [comment]
@springdo @adamclark I think @pabrahamsson just recently had his changes merged upstream to get the Hashicorp Vault helm chart working on OpenShift. I believe we're already using this internally, so maybe we can look to get that included here as well.

**Comment by pabrahamsson** [comment]
With the above mentioned merge and some other updates I now have a fork of the upstream Hashicorp Vault helm chart that I believe would work fine with UJ.
A bit of a concern however, I'm anticipating my fork not being merged upstream for a while due to testing issues (can't use `helm template` disconnected when using [lookup](https://github.com/helm/helm/pull/6752)).
Would you still want this contributed to [rht-labs/helm-charts](/rht-labs/helm-charts) while I work on getting it merged upstream?

**Comment by tylerauerbeck** [comment]
@pabrahamsson I believe this is the approach that we've taken with other charts while we've worked on gettings things upstreamed, so that should work here as well.

**Comment by springdo** [comment]
@richardwalkerdev has done a ton of work around hashicorp on openshift. Here is his detailed approach which could help us move this ticket forwards....

https://www.richardwalker.dev/guides/vault_podman_rest/

👏👏👏 Good Job Richard 👏👏👏
